
#define SCREEN_WIDTH  	1280 //1280 640
#define SCREEN_HEIGHT 	720	 //720  480

#define SCREEN_MIDDLE SCREEN_WIDTH/2-TILE_SIZE/2

#define MAX_TILES    8
#define TILE_SIZE    40
#define TILE_FILE_SIZE 16
#define MAP_RENDER_WIDTH    SCREEN_WIDTH/TILE_SIZE
#define MAP_RENDER_HEIGHT   SCREEN_HEIGHT/TILE_SIZE

#define PLAYER_SPEED 4

#define V_SYNC
#define TICK 16

#define WINDOW_BORDERLESS
//#define WINDOW_FULLSCREEN

// DEBUG //
//#define DEBUG_SHOW_COMMAND
#define DEBUG_SHOW_HITBOX
//#define DEBUG_SHOW_FPS
//#define DEBUG_SHOW_XY
#define DEBUG_SHOW_SYSTEM
//#define DEBUG_GET_LOG

